[tool.poetry]
name = "torch-test"
version = "0.1.0"
description = ""
authors = ["shunsuke.hishida <shunsuke.hishida@dena.jp>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.11"
torch = "^2.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
